### ISSUE TITLE
How do I install the plugin and is it already finished?

### ISSUE THREAD

**Issue by FlashiFlasche** [Atten007/IslandCraft-Reborn#1]
I really wanted to use IslandCraft on a 1.18.1 Minecraft server but I can't compile the plugin.

I tried to compiling it with maven via terminal and with eclipse maven builder. I even put the files manually into a jar file but still doesn't work because it cannot find the main path written in the plugin.yml 

Is there a way to get this plugin?

**Comment by Atten007** [comment]
Hi Flashi,

the plug-in isn’t finished yet, but when I’ve time, I‘m going to keep working on this plug-in. And in the plugin.yml, I want to fix this very s****y error, sorry for the bad word, I‘m saying it because my maven has also occurred this error. Have a nice day,

sincerely yours,
Atten007 😊

**Comment by FlashiFlasche** [comment]
what kind of error do you get?

Is it the invalid character error? Its because you are using in the first row a space character ("IslandCraft Reborn") and fixing that is by renaming it to "IslandCraftReborn".

But after I did that, the plugin.yml doesn't know what the main class is.

**Comment by Atten007** [comment]
I've removed all files from the repo, they'll back very soon, when IslandCraft-Bukkit-1.0.9 is finished! In the meantime you can create a PaperMC 1.8.8 server with ViaVersion and IslandCraft installed on it.
